spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/backend
spring.datasource.username=postgres
spring.datasource.password=q#r^u(pAeG
spring.jpa.hibernate.ddl-auto=update